notifications:
  email:
    false

stages:
  - test
  - trigger

env:
  - TARGET: x86_64-unknown-linux-gnu
  - TARGET: i686-unknown-linux-gnu
  - TARGET: aarch64-linux-android
  - TARGET: arm-linux-androideabi
  - TARGET: x86_64-linux-android
  # - TARGET: i686-linux-android

jobs:
  include:
    - stage: trigger
      name: Astral Engine
      language: shell
      script : |
        body="{\"request\":{\"branch\":\"master\",\"message\":\"Test latest rust version\"}}"
        curl -s -X POST \
          -H "Content-Type:application/json" \
          -H "Accept:application/json" \
          -H "Travis-API-Version:3" \
          -H "Authorization:token ${TRAVIS_TOKEN}" \
          -d "$body" \
          https://api.travis-ci.org/repo/astral-engine%2Fastral/requests

install: |
  git clone https://github.com/docker-library/official-images.git ~/official-images
  TOOLCHAINS=( "stable" "beta" "nightly" )

before_script: |
  RUSTC_STABLE=$(docker run astralengine/$TARGET:stable rustc --version || true)
  RUSTC_BETA=$(docker run astralengine/$TARGET:beta rustc --version || true)
  RUSTC_NIGHTLY=$(docker run astralengine/$TARGET:nightly rustc --version || true)
  echo $RUSTC_STABLE
  echo $RUSTC_BETA
  echo $RUSTC_NIGHTLY

script: |
  for TOOLCHAIN in "${TOOLCHAINS[@]}"; do
    travis_fold start "$TOOLCHAIN"
    travis_time_start
    travis_retry docker build \
      --rm \
      --pull \
      --cache-from astralengine/$TARGET:$TOOLCHAIN \
      --file $TARGET/Dockerfile \
      --tag astralengine/$TARGET:$TOOLCHAIN \
      --build-arg TOOLCHAIN=$TOOLCHAIN \
      --build-arg DATE="`date`" \
      . || exit
    ~/official-images/test/run.sh astralengine/$TARGET:$TOOLCHAIN
    travis_time_finish
    travis_fold end "$TOOLCHAIN"
  done

after_success: |
  RUSTC_STABLE_NEW=$(docker run astralengine/$TARGET:stable rustc --version || true)
  RUSTC_BETA_NEW=$(docker run astralengine/$TARGET:beta rustc --version || true)
  RUSTC_NIGHTLY_NEW=$(docker run astralengine/$TARGET:nightly rustc --version || true)
  echo $RUSTC_STABLE_NEW
  echo $RUSTC_BETA_NEW
  echo $RUSTC_NIGHTLY_NEW

before_deploy: |
  VERSION=$(echo $RUSTC_STABLE_NEW | awk '{ print $2 }')
  if [[ $RUSTC_STABLE_NEW == $RUSTC_STABLE && $TRAVIS_EVENT_TYPE == cron ]]; then
    docker rmi -f astralengine/$TARGET:stable
  else
    docker tag astralengine/$TARGET:stable astralengine/$TARGET:$VERSION
    docker tag astralengine/$TARGET:stable astralengine/$TARGET:latest
  fi
  if [[ $RUSTC_BETA_NEW == $RUSTC_BETA && $TRAVIS_EVENT_TYPE == cron ]]; then
    docker rmi -f astralengine/$TARGET:beta
  fi
  if [[ $RUSTC_NIGHTLY_NEW == $RUSTC_NIGHTLY && $TRAVIS_EVENT_TYPE == cron ]]; then
    docker rmi -f astralengine/$TARGET:nightly
  fi
  echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
deploy:
  provider: script
  script: docker push astralengine/$TARGET || true
  on:
    branch: master

after_script: docker images
